# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: walyorg
# "service" is the name of this project. This will also be added to your AWS resource names.
service: user-service

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  stage: "dev"
  region: "us-east-1"
  httpApi:
    cors: true
  environment:
    DB_USER: ${env:DB_USER}
    DB_NAME: ${env:DB_NAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}

functions:
  signup:
    handler: app/handler.signUp
    events:
      - httpApi:
          path: /signup
          method: post

  signin:
    handler: app/handler.signIn
    events:
      - httpApi:
          path: /signin
          method: post

  verify:
    handler: app/handler.verify
    events:
      - httpApi:
          path: /verify
          method: post

  profile:
    handler: app/handler.profile
    events:
      - httpApi:
          path: /user
          method: post
      - httpApi:
          path: /user
          method: put
      - httpApi:
          path: /user
          method: get

  cart:
    handler: app/handler.cart
    events:
      - httpApi:
          path: /cart
          method: post
      - httpApi:
          path: /cart
          method: put
      - httpApi:
          path: /cart
          method: get

  payment:
    handler: app/handler.payment
    events:
      - httpApi:
          path: /payment
          method: post
      - httpApi:
          path: /payment
          method: put
      - httpApi:
          path: /payment
          method: get

plugins:
  - serverless-offline
